const effects = {
  rain: "Rain",
  chatter: "Chatter",
  nature: "Nature",
  birdsChirping: "Birds Chirping",
  cityTraffic: "City Traffic",
  stormyNight: "Stormy Night",
  fan: "Fan",
  whiteNoise: "White Noise",
  thunder: "Thunder",
  ambience: "Ambience",
  ocean: "Ocean",
  water: "Water",
  airplane: "Airplane",
  clock: "Clock",
  fireplace: "Fireplace",
  keyboard: "Keyboard",
  morning: "Morning",
  snow: "Snow",
  summerNight: "Summer Night",
  train: "Train",
  underwater: "Underwater",
};

export { effects };
