import {
  FaPlay,
  FaPause,
  FaStickyNote,
  FaUserAlt,
  FaMedal,
  FaHeadphones,
  FaCrown,
  FaLock,
} from "react-icons/fa";
import {
  BsFillSkipBackwardFill,
  BsSkipForwardFill,
  BsCloudRain,
  BsTree,
  BsPhoneFill,
  BsFillCalendarDateFill,
  BsInfoCircle,
  BsCaretUpFill,
  BsCaretDownFill,
  BsFillInfoCircleFill,
  BsSpotify,
  BsSoundwave,
  BsLightningCharge,
  BsArrowRepeat,
  BsCheck2,
  BsKeyboard,
  BsAirplane,
  BsTrainFront,
} from "react-icons/bs";
import {
  IoVolumeMedium,
  IoVolumeMute,
  IoVolumeOff,
  IoCloseOutline,
  IoThunderstormOutline,
  IoBookSharp,
  IoCloudyNightOutline,
} from "react-icons/io5";
import {
  RiSoundModuleFill,
  RiFullscreenFill,
  RiFullscreenExitLine,
  RiPlayListFill,
} from "react-icons/ri";
import {
  HiOutlineChatBubbleLeftRight,
  HiOutlineBuildingOffice2,
  HiClipboardDocumentList,
} from "react-icons/hi2";
import { HiTemplate } from "react-icons/hi";
import { SlSocialTwitter } from "react-icons/sl";
import { WiNightAltStormShowers } from "react-icons/wi";
import { LuFan, LuWaves } from "react-icons/lu";
import { CgEditNoise } from "react-icons/cg";
import { GiTacos, GiBigWave } from "react-icons/gi";
import {
  MdLandscape,
  MdDelete,
  MdModeEdit,
  MdOutlineDone,
  MdOutlineMenu,
  MdSettings,
  MdTimer,
  MdEmail,
  MdOutlineWaterDrop,
  MdLibraryMusic,
} from "react-icons/md";
import {
  AiFillTool,
  AiOutlineGoogle,
  AiFillInstagram,
  AiOutlineClockCircle,
  AiOutlineFire,
} from "react-icons/ai";
import { FiPlus } from "react-icons/fi";
import { FaCommentDots, FaHandsHelping } from "react-icons/fa";
import { RxCaretLeft, RxCaretRight, RxReset, RxTimer } from "react-icons/rx";
import { PiMoonFill, PiSunHorizonLight, PiSnowflakeThin } from "react-icons/pi";
import { VscDebugRestart } from "react-icons/vsc";
import { TbSubmarine } from "react-icons/tb";

export {
  FaPause,
  FaPlay,
  BsFillSkipBackwardFill,
  BsSkipForwardFill,
  IoVolumeMedium,
  IoVolumeMute,
  RiSoundModuleFill,
  IoVolumeOff,
  BsCloudRain,
  BsTree,
  IoCloseOutline,
  HiOutlineChatBubbleLeftRight,
  HiOutlineBuildingOffice2,
  SlSocialTwitter,
  RiFullscreenFill,
  RiFullscreenExitLine,
  WiNightAltStormShowers,
  LuFan,
  CgEditNoise,
  IoThunderstormOutline,
  LuWaves,
  GiTacos,
  MdLandscape,
  BsPhoneFill,
  AiFillTool,
  AiOutlineGoogle,
  BsFillCalendarDateFill,
  FaStickyNote,
  HiClipboardDocumentList,
  BsInfoCircle,
  GiBigWave,
  FiPlus,
  MdDelete,
  MdModeEdit,
  MdOutlineDone,
  BsCaretUpFill,
  BsCaretDownFill,
  MdOutlineMenu,
  MdSettings,
  FaCommentDots,
  BsFillInfoCircleFill,
  MdTimer,
  RxCaretLeft,
  RxCaretRight,
  RxReset,
  FaHandsHelping,
  BsSpotify,
  FaUserAlt,
  FaMedal,
  AiFillInstagram,
  MdEmail,
  MdOutlineWaterDrop,
  PiMoonFill,
  FaHeadphones,
  FaCrown,
  IoBookSharp,
  MdLibraryMusic,
  RiPlayListFill,
  BsSoundwave,
  HiTemplate,
  VscDebugRestart,
  RxTimer,
  BsLightningCharge,
  BsArrowRepeat,
  BsCheck2,
  BsKeyboard,
  BsAirplane,
  AiOutlineClockCircle,
  AiOutlineFire,
  PiSunHorizonLight,
  PiSnowflakeThin,
  IoCloudyNightOutline,
  BsTrainFront,
  TbSubmarine,
  FaLock,
};
